version: "3"
services:
  
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /backend
    volumes:
        - ./:/backend
    expose:
      - 8000
    ports:
      - "8000:8000"