# Generated by Django 5.1.2 on 2024-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField(unique=True)),
                ('surya_present', models.BooleanField(default=False)),
                ('moon_present', models.BooleanField(default=False)),
                ('mangal_present', models.BooleanField(default=False)),
                ('budh_present', models.BooleanField(default=False)),
                ('guru_present', models.BooleanField(default=False)),
                ('shukra_present', models.BooleanField(default=False)),
                ('shani_present', models.BooleanField(default=False)),
                ('rahu_present', models.BooleanField(default=False)),
                ('ketu_present', models.BooleanField(default=False)),
                ('surya_drishti', models.BooleanField(default=False)),
                ('moon_drishti', models.BooleanField(default=False)),
                ('mangal_drishti', models.BooleanField(default=False)),
                ('budh_drishti', models.BooleanField(default=False)),
                ('guru_drishti', models.BooleanField(default=False)),
                ('shukra_drishti', models.BooleanField(default=False)),
                ('shani_drishti', models.BooleanField(default=False)),
                ('rahu_drishti', models.BooleanField(default=False)),
                ('ketu_drishti', models.BooleanField(default=False)),
                ('rashi', models.CharField(max_length=50)),
                ('results', models.TextField()),
            ],
        ),
    ]
