# Generated by Django 5.1.2 on 2024-10-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_alter_house_house_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashaPhal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=[('Surya', 'Surya'), ('Moon', 'Moon'), ('Mangal', 'Mangal'), ('Budh', 'Budh'), ('Guru', 'Guru'), ('Shukra', 'Shukra'), ('Shani', 'Shani'), ('Rahu', 'Rahu'), ('Ketu', 'Ketu')], max_length=50)),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AntarDashaPhal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=[('Surya', 'Surya'), ('Moon', 'Moon'), ('Mangal', 'Mangal'), ('Budh', 'Budh'), ('Guru', 'Guru'), ('Shukra', 'Shukra'), ('Shani', 'Shani'), ('Rahu', 'Rahu'), ('Ketu', 'Ketu')], max_length=50)),
                ('results', models.TextField()),
                ('dasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrology.dashaphal')),
            ],
        ),
        migrations.CreateModel(
            name='PratyantarDashaPhal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=[('Surya', 'Surya'), ('Moon', 'Moon'), ('Mangal', 'Mangal'), ('Budh', 'Budh'), ('Guru', 'Guru'), ('Shukra', 'Shukra'), ('Shani', 'Shani'), ('Rahu', 'Rahu'), ('Ketu', 'Ketu')], max_length=50)),
                ('results', models.TextField()),
                ('antardasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrology.antardashaphal')),
            ],
        ),
    ]
