# Generated by Django 5.1.2 on 2024-10-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_dashaphal_antardashaphal_pratyantardashaphal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rashi',
            field=models.CharField(choices=[('None', 'None'), ('Mesh', 'Mesh'), ('Vrishabh', 'Vrishabh'), ('Mithun', 'Mithun'), ('Kark', 'Kark'), ('Simha', 'Simha'), ('Kanya', 'Kanya'), ('Tula', 'Tula'), ('Vrischik', 'Vrischik'), ('Dhanu', 'Dhanu'), ('Makar', 'Makar'), ('Kumbh', 'Kumbh'), ('Meen', 'Meen')], default='None', max_length=50),
        ),
    ]
