# Generated by Django 5.1.2 on 2024-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_alter_house_rashi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashaPhal',
            new_name='MahaDashaPhal',
        ),
        migrations.AddField(
            model_name='house',
            name='lagna_planet',
            field=models.CharField(choices=[('Surya', 'Surya'), ('Moon', 'Moon'), ('Mangal', 'Mangal'), ('Budh', 'Budh'), ('Guru', 'Guru'), ('Shukra', 'Shukra'), ('Shani', 'Shani'), ('Rahu', 'Rahu'), ('Ketu', 'Ketu')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='lagna_raashi',
            field=models.CharField(choices=[('None', 'None'), ('Mesh', 'Mesh'), ('Vrishabh', 'Vrishabh'), ('Mithun', 'Mithun'), ('Kark', 'Kark'), ('Simha', 'Simha'), ('Kanya', 'Kanya'), ('Tula', 'Tula'), ('Vrischik', 'Vrischik'), ('Dhanu', 'Dhanu'), ('Makar', 'Makar'), ('Kumbh', 'Kumbh'), ('Meen', 'Meen')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='nakshtra',
            field=models.CharField(choices=[('None', 'None'), ('Ashwini', 'Ashwini'), ('Bharani', 'Bharani'), ('Kritika', 'Kritika'), ('Rohini', 'Rohini'), ('Mrigashira', 'Mrigashira'), ('Ardra', 'Ardra'), ('Punarvasu', 'Punarvasu'), ('Pushya', 'Pushya'), ('Ashlesha', 'Ashlesha'), ('Magha', 'Magha'), ('Purva Phalguni', 'Purva Phalguni'), ('Uttara Phalguni', 'Uttara Phalguni'), ('Hasta', 'Hasta'), ('Chitra', 'Chitra'), ('Swati', 'Swati'), ('Vishakha', 'Vishakha'), ('Anuradha', 'Anuradha'), ('Jyeshtha', 'Jyeshtha'), ('Mula', 'Mula'), ('Purva Ashadha', 'Purva Ashadha'), ('Uttara Ashadha', 'Uttara Ashadha'), ('Shravana', 'Shravana'), ('Dhanishta', 'Dhanishta'), ('Shatabhisha', 'Shatabhisha'), ('Purva Bhadrapada', 'Purva Bhadrapada'), ('Uttara Bhadrapada', 'Uttara Bhadrapada'), ('Revati', 'Revati')], default='None', max_length=50),
        ),
    ]
