# Generated by Django 5.1.2 on 2024-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0005_rename_dashaphal_mahadashaphal_house_lagna_planet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='element',
            field=models.CharField(choices=[('None', 'None'), ('Fire', 'Fire'), ('Earth', 'Earth'), ('Air', 'Air'), ('Water', 'Water')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='nakshtra_pada',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_no',
            field=models.IntegerField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')]),
        ),
    ]
